Fix: NgRenderIn directive
Adroit-Group/ng-tools pull request #49
Opened 2023-01-10 13:09 UTC by JohnasBroda

+ Fixed the paltform input type of the NgRenderin directive to make the platform input specifiable from the component HTML.
+ Changed NgRenderingElse input name to: NgRenderInOr to make it bindable in the component HTML microsyntax.
+ Updated Platform Executor decoraotrs that uses the EApplicationPlatform enum.
+ Renamed worker related keys of the EApplicationPlatform const to make it consistent.
+ Exported EApplicationPlatform const from the lib package

2023-01-10 13:50 UTC, krisztofer-kunc requested changes

2023-01-11 08:21 UTC, JohnasBroda commented on libs/ng-utils/src/lib/directives/ng-render-in.directive.ts
> + * <app-splash-screen *ngRenderInServer="or ssrTpl"></app-splash-screen>
Nice catch ;)

2023-01-11 08:47 UTC, krisztofer-kunc requested changes

2023-01-11 08:47 UTC, krisztofer-kunc commented on libs/ng-utils/src/lib/directives/ng-render-in.directive.ts
> + * <ng-template #ssrTpl>...</ng-template>
```suggestion
 * <ng-template #browserTpl>...</ng-template>
```

2023-02-24 10:39 UTC, krisztofer-kunc approved these changes

2023-02-24 11:47 UTC, krisztofer-kunc approved these changes

2023-02-24 11:48 UTC, merged